export const customersData = () => {
  const data = [
  {
    customerID: 1,
    affiliate: 'Gy Test Contains leaks',
    referral: '28 Nov 2022',
    revenue: '+$356.05',
    paidpayouts: '$0.00',
    unpaidpayouts: 35.61,
    readypayouts: 35.61,
    breakdown: '',
    type: '',
    selected: false,
    actions: '',
    payment: 'Store Credit',
  },
  {
    customerID: 2,
    affiliate: 'Dwight Wisoky',
    referral: '28 Nov 2022',
    revenue: '+$267.04',
    paidpayouts: '$0.00',
    unpaidpayouts: 26.7,
    readypayouts: 0.00,
    breakdown: '',
    type: '',
    selected: false,
    actions: '',
    payment: 'Store Credit',
  },
  {
    customerID: 3,
    affiliate: 'Zack Treutel',
    referral: '28 Nov 2022',
    revenue: '+$161.96',
    paidpayouts: '$0.00',
    unpaidpayouts: 16.2,
    readypayouts: 16.20,
    breakdown: '',
    type: '',
    selected: false,
    actions: '',
    payment: 'Store Credit',
  },
  {
    customerID: 4,
    affiliate: 'Hilma Welch',
    referral: '28 Nov 2022',
    revenue: '+$126.93',
    paidpayouts: '$0.00',
    unpaidpayouts: 12.69,
    readypayouts: 0.00,
    breakdown: '',
    type: '',
    selected: false,
    actions: '',
    payment: 'Cash',
  },
  {
    customerID: 5,
    affiliate: 'Adam Kohler',
    referral: '28 Nov 2022',
    revenue: '+$99.69',
    paidpayouts: '$0.00',
    unpaidpayouts: 9.97,
    readypayouts: 0.00,
    breakdown: '',
    type: '',
    selected: false,
    actions: '',
    payment: 'Cash',
  },
  ];
 return [...data]
}